"""
convert_rsna.py - RSNA Pneumonia Detection Dataset Converter

Parses RSNA stage_2_train_labels.csv and DICOM images into normalized
YOLO format (.txt labels with: class_id x_center y_center width height).
Also generates a dataset.yaml file for YOLOv8 training.

Usage:
    python convert_rsna.py \
        --csv_path /path/to/stage_2_train_labels.csv \
        --dicom_dir /path/to/stage_2_train_images \
        --output_dir ./dataset \
        --val_split 0.2
"""

import os
import argparse
import shutil
from pathlib import Path

import pandas as pd
import pydicom
import cv2
import numpy as np
from sklearn.model_selection import train_test_split
from tqdm import tqdm


def parse_args():
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Convert RSNA Pneumonia DICOM dataset to YOLO format"
    )
    parser.add_argument(
        "--csv_path",
        type=str,
        required=True,
        help="Path to stage_2_train_labels.csv",
    )
    parser.add_argument(
        "--dicom_dir",
        type=str,
        required=True,
        help="Path to directory containing DICOM images",
    )
    parser.add_argument(
        "--output_dir",
        type=str,
        default="./dataset",
        help="Output directory for YOLO-formatted dataset (default: ./dataset)",
    )
    parser.add_argument(
        "--val_split",
        type=float,
        default=0.2,
        help="Fraction of data to use for validation (default: 0.2)",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed for train/val split (default: 42)",
    )
    return parser.parse_args()


def dicom_to_png(dicom_path: str) -> np.ndarray:
    """
    Read a DICOM file and convert it to an 8-bit grayscale numpy array.

    Args:
        dicom_path: Path to the DICOM (.dcm) file.

    Returns:
        8-bit grayscale image as a numpy array.
    """
    ds = pydicom.dcmread(dicom_path)
    pixel_array = ds.pixel_array.astype(np.float32)

    # Normalize to 0-255 range
    pixel_min = pixel_array.min()
    pixel_max = pixel_array.max()
    if pixel_max > pixel_min:
        pixel_array = (pixel_array - pixel_min) / (pixel_max - pixel_min) * 255.0
    else:
        pixel_array = np.zeros_like(pixel_array)

    return pixel_array.astype(np.uint8)


def convert_bbox_to_yolo(x, y, w, h, img_width, img_height):
    """
    Convert RSNA bounding box (x, y, width, height) to YOLO normalized format
    (x_center, y_center, width, height) where all values are in [0, 1].

    Args:
        x: Top-left x coordinate (pixels).
        y: Top-left y coordinate (pixels).
        w: Bounding box width (pixels).
        h: Bounding box height (pixels).
        img_width: Image width (pixels).
        img_height: Image height (pixels).

    Returns:
        Tuple of (x_center, y_center, width, height) normalized to [0, 1].
    """
    x_center = (x + w / 2.0) / img_width
    y_center = (y + h / 2.0) / img_height
    norm_w = w / img_width
    norm_h = h / img_height

    # Clamp values to [0, 1]
    x_center = max(0.0, min(1.0, x_center))
    y_center = max(0.0, min(1.0, y_center))
    norm_w = max(0.0, min(1.0, norm_w))
    norm_h = max(0.0, min(1.0, norm_h))

    return x_center, y_center, norm_w, norm_h


def create_directory_structure(output_dir: str):
    """
    Create the YOLO dataset directory structure.

    Args:
        output_dir: Root output directory for the dataset.
    """
    for split in ["train", "val"]:
        os.makedirs(os.path.join(output_dir, "images", split), exist_ok=True)
        os.makedirs(os.path.join(output_dir, "labels", split), exist_ok=True)


def generate_dataset_yaml(output_dir: str, yaml_path: str = "dataset.yaml"):
    """
    Generate the dataset.yaml file required by YOLOv8.

    Args:
        output_dir: Root dataset directory.
        yaml_path: Output path for the YAML file.
    """
    abs_output_dir = os.path.abspath(output_dir)
    yaml_content = f"""# RSNA Pneumonia Detection - YOLOv8 Dataset Configuration
# Auto-generated by convert_rsna.py

path: {abs_output_dir}
train: images/train
val: images/val

# Classes
names:
  0: Pneumonia

# Number of classes
nc: 1
"""
    with open(yaml_path, "w") as f:
        f.write(yaml_content)

    print(f"[INFO] dataset.yaml saved to: {yaml_path}")


def main():
    """Main conversion pipeline."""
    args = parse_args()

    csv_path = args.csv_path
    dicom_dir = args.dicom_dir
    output_dir = args.output_dir
    val_split = args.val_split
    seed = args.seed

    # ------------------------------------------------------------------
    # 1. Load and parse CSV
    # ------------------------------------------------------------------
    print(f"[INFO] Loading CSV from: {csv_path}")
    df = pd.read_csv(csv_path)
    print(f"[INFO] Total rows in CSV: {len(df)}")

    # The CSV has columns: patientId, x, y, width, height, Target
    # Target == 1 means pneumonia is present and bbox is valid
    # Target == 0 means no pneumonia (negative sample, bbox columns are NaN)
    positive_df = df[df["Target"] == 1].copy()
    negative_ids = df[df["Target"] == 0]["patientId"].unique()
    positive_ids = positive_df["patientId"].unique()

    print(f"[INFO] Positive samples (with bounding boxes): {len(positive_ids)}")
    print(f"[INFO] Negative samples (no pneumonia): {len(negative_ids)}")

    # Group bounding boxes by patient ID
    bbox_dict = {}
    for _, row in positive_df.iterrows():
        pid = row["patientId"]
        if pid not in bbox_dict:
            bbox_dict[pid] = []
        bbox_dict[pid].append(
            (row["x"], row["y"], row["width"], row["height"])
        )

    # ------------------------------------------------------------------
    # 2. Train/Val split on patient IDs
    # ------------------------------------------------------------------
    all_patient_ids = list(set(list(positive_ids) + list(negative_ids)))
    train_ids, val_ids = train_test_split(
        all_patient_ids, test_size=val_split, random_state=seed
    )

    print(f"[INFO] Train patients: {len(train_ids)}, Val patients: {len(val_ids)}")

    # ------------------------------------------------------------------
    # 3. Create directory structure
    # ------------------------------------------------------------------
    create_directory_structure(output_dir)

    # ------------------------------------------------------------------
    # 4. Process each patient: convert DICOM -> PNG, create YOLO labels
    # ------------------------------------------------------------------
    split_map = {}
    for pid in train_ids:
        split_map[pid] = "train"
    for pid in val_ids:
        split_map[pid] = "val"

    stats = {"train_pos": 0, "train_neg": 0, "val_pos": 0, "val_neg": 0, "skipped": 0}

    print("[INFO] Converting DICOM images and generating YOLO labels...")
    for pid in tqdm(all_patient_ids, desc="Processing patients"):
        # Locate DICOM file
        dicom_path = os.path.join(dicom_dir, f"{pid}.dcm")
        if not os.path.exists(dicom_path):
            stats["skipped"] += 1
            continue

        split = split_map[pid]

        # Convert DICOM to PNG
        img = dicom_to_png(dicom_path)
        img_h, img_w = img.shape[:2]

        # Save image as PNG
        img_out_path = os.path.join(output_dir, "images", split, f"{pid}.png")
        cv2.imwrite(img_out_path, img)

        # Create YOLO label file
        label_out_path = os.path.join(output_dir, "labels", split, f"{pid}.txt")

        if pid in bbox_dict:
            # Positive sample: write bounding box annotations
            with open(label_out_path, "w") as f:
                for x, y, w, h in bbox_dict[pid]:
                    xc, yc, nw, nh = convert_bbox_to_yolo(
                        x, y, w, h, img_w, img_h
                    )
                    # class_id=0 for Pneumonia
                    f.write(f"0 {xc:.6f} {yc:.6f} {nw:.6f} {nh:.6f}\n")
            stats[f"{split}_pos"] += 1
        else:
            # Negative sample: empty label file (background)
            with open(label_out_path, "w") as f:
                pass  # empty file signals no detections
            stats[f"{split}_neg"] += 1

    # ------------------------------------------------------------------
    # 5. Generate dataset.yaml
    # ------------------------------------------------------------------
    yaml_output_path = os.path.join(os.path.dirname(output_dir) or ".", "dataset.yaml")
    generate_dataset_yaml(output_dir, yaml_output_path)

    # ------------------------------------------------------------------
    # 6. Print summary
    # ------------------------------------------------------------------
    print("\n" + "=" * 60)
    print("RSNA -> YOLO Conversion Complete!")
    print("=" * 60)
    print(f"  Output directory : {os.path.abspath(output_dir)}")
    print(f"  Train positives  : {stats['train_pos']}")
    print(f"  Train negatives  : {stats['train_neg']}")
    print(f"  Val positives    : {stats['val_pos']}")
    print(f"  Val negatives    : {stats['val_neg']}")
    print(f"  Skipped (no DCM) : {stats['skipped']}")
    print(f"  dataset.yaml     : {os.path.abspath(yaml_output_path)}")
    print("=" * 60)


if __name__ == "__main__":
    main()
