"""
Gemini Report Generation Service

Calls the Google Gemini API (via the official google-genai SDK) to produce
a structured radiology report that SUMMARISES the three AI model outputs.

Key safety constraints enforced in the prompt:
  - Gemini MUST NOT invent findings absent from model outputs.
  - Gemini MUST NOT claim certainty beyond the model evidence.
  - Gemini is NOT independently diagnosing the patient.
  - Output MUST follow the RadiologyReport JSON schema exactly.

Environment variables (set in .env or shell):
    GEMINI_API_KEY   Google AI Studio / Vertex API key (required in production).
    GEMINI_MODEL     Model name — default: gemini-2.0-flash
    GEMINI_MOCK      Set to "true" to skip real API calls (no key needed).

Usage:
    from app.services.gemini_service import generate_report
    report = generate_report(yolo, densenet, multimodal, clinical_notes)
"""

import json
import os
from typing import Optional

from app.schemas.prediction import RadiologyReport

# ── Read config from environment ────────────────────────────────
GEMINI_API_KEY: str = os.getenv("GEMINI_API_KEY", "")
GEMINI_MODEL: str = os.getenv("GEMINI_MODEL", "gemini-2.0-flash")
GEMINI_MOCK: bool = os.getenv("GEMINI_MOCK", "false").strip().lower() == "true"


# ── Prompt template ─────────────────────────────────────────────
_PROMPT_TEMPLATE = """\
You are an AI assistant helping to generate a structured radiology report summary.

IMPORTANT CONSTRAINTS — follow these strictly:
1. You are a report-SUMMARISATION layer, not an independent diagnostic system.
2. Do NOT invent findings that are not present in the model outputs below.
3. Do NOT claim certainty beyond what the model evidence supports.
4. You are NOT independently diagnosing the patient.
5. Your output must follow the JSON schema exactly as instructed.

INPUTS PROVIDED TO YOU:
- Clinical Notes from Clinician : {clinical_notes}
- YOLO Detection Results        : {yolo_result}
- DenseNet Similarity Results   : {densenet_result}
- Multimodal Analysis Results   : {multimodal_result}

Based ONLY on the model outputs above, fill in the four JSON fields:
  impression       — A concise overall impression derived from the model outputs.
  findings         — Specific findings reported by each model.
  recommendations  — Suggested follow-up actions, if the models indicate abnormalities.
  model_summary    — Brief technical summary of what each model detected.
"""


def _build_prompt(
    yolo_result: dict,
    densenet_result: dict,
    multimodal_result: dict,
    clinical_notes: Optional[str],
) -> str:
    """Format the constrained prompt with actual model outputs."""
    return _PROMPT_TEMPLATE.format(
        clinical_notes=clinical_notes or "None provided",
        yolo_result=json.dumps(yolo_result, indent=2),
        densenet_result=json.dumps(densenet_result, indent=2),
        multimodal_result=json.dumps(multimodal_result, indent=2),
    )


def _mock_report() -> RadiologyReport:
    """
    Return a hardcoded mock RadiologyReport.
    Used when GEMINI_MOCK=true — schema is identical to the real response.
    """
    return RadiologyReport(
        impression=(
            "[MOCK] No significant findings detected. "
            "All model services returned placeholder outputs."
        ),
        findings=(
            "[MOCK] "
            "YOLO: 0 detections. "
            "DenseNet/FAISS: 0 similar cases retrieved. "
            "Multimodal: no pathology probabilities computed. "
            "This report was generated by the mock fallback (GEMINI_MOCK=true)."
        ),
        recommendations=(
            "[MOCK] Replace placeholder model services with real implementations "
            "before clinical use. No recommendations can be made from mock outputs."
        ),
        model_summary=(
            "[MOCK] All three model services (YOLO, DenseNet, Multimodal) "
            "returned stub responses. Real model integration is pending."
        ),
    )


def generate_report(
    yolo_result: dict,
    densenet_result: dict,
    multimodal_result: dict,
    clinical_notes: Optional[str] = None,
) -> RadiologyReport:
    """
    Generate a structured radiology report by summarising model outputs.

    If GEMINI_MOCK=true, returns a mock report without any API call.
    Otherwise, calls the Gemini API with a structured-output configuration
    so the response is parsed directly into the RadiologyReport schema.

    Args:
        yolo_result:       Output from call_yolo().
        densenet_result:   Output from call_densenet().
        multimodal_result: Output from call_multimodal().
        clinical_notes:    Optional clinician text.

    Returns:
        A validated RadiologyReport Pydantic instance.

    Raises:
        ValueError: If GEMINI_MOCK=false and GEMINI_API_KEY is not set.
        Exception:  Propagates any google-genai API errors.
    """
    if GEMINI_MOCK:
        return _mock_report()

    if not GEMINI_API_KEY:
        raise ValueError(
            "GEMINI_API_KEY environment variable is not set. "
            "Either set a valid key or use GEMINI_MOCK=true for local testing."
        )

    # ── Real Gemini call ─────────────────────────────────────────
    # google-genai is the official SDK (not the deprecated google-generativeai).
    from google import genai
    from google.genai import types

    client = genai.Client(api_key=GEMINI_API_KEY)

    prompt = _build_prompt(yolo_result, densenet_result, multimodal_result, clinical_notes)

    response = client.models.generate_content(
        model=GEMINI_MODEL,
        contents=prompt,
        config=types.GenerateContentConfig(
            response_mime_type="application/json",
            response_schema=RadiologyReport,
        ),
    )

    # Gemini returns structured JSON matching the RadiologyReport schema
    report_data = json.loads(response.text)
    return RadiologyReport(**report_data)
