"""
SQLAlchemy ORM models.

Defines the `prediction_audit` table used to log every prediction
request for traceability and debugging.

Raw X-ray image bytes are NOT stored here.
Model outputs and the Gemini report are stored as JSON strings (Text columns)
so the schema works with both SQLite and PostgreSQL.
"""

from sqlalchemy import Column, Integer, String, Text, DateTime
from sqlalchemy.sql import func

from app.db.database import Base


class PredictionAudit(Base):
    """
    Audit record for one prediction request.

    Created automatically after every successful POST /api/v1/predict call.
    Retrievable via GET /api/v1/audit/{request_id}.
    """

    __tablename__ = "prediction_audit"

    id = Column(Integer, primary_key=True, index=True)
    """Auto-incrementing primary key."""

    request_id = Column(String(36), unique=True, index=True, nullable=False)
    """UUID string assigned to each prediction request."""

    filename = Column(String(255), nullable=True)
    """Original filename of the uploaded X-ray image."""

    clinical_notes = Column(Text, nullable=True)
    """Free-text clinical context provided by the clinician (optional)."""

    yolo_result = Column(Text, nullable=True)
    """JSON-encoded output from the YOLO detection service."""

    densenet_result = Column(Text, nullable=True)
    """JSON-encoded output from the DenseNet/FAISS similarity service."""

    multimodal_result = Column(Text, nullable=True)
    """JSON-encoded output from the multimodal analysis service."""

    gemini_report = Column(Text, nullable=True)
    """JSON-encoded RadiologyReport generated by Gemini."""

    created_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    """Timestamp when the audit record was created (set by the database)."""
